### ISSUE TITLE
使用我的仓库按照说明把条目和插件放进去就可以了

### ISSUE THREAD

**Issue by Zacharia2** [dongrentianyu/github111#1]
https://github.com/Zacharia2/TW5-T-ONLINE

**Comment by Zacharia2** [comment]
有问题可以在我的仓库提issue

**Comment by dongrentianyu** [comment]
这个是测试项目，回头会删除的。不过看样子，你能部署成功？昨天我试了好几种方式都无法部署成功，除了旧版的morden插件。现在更新了插件，我昨天测试没有部署成功。

**Comment by Zacharia2** [comment]
废话，专门做的，哈哈哈

**Comment by dongrentianyu** [comment]
还有，morden插件更新了。部署方式和之前的不一样了。你可以去试一下，能不能成功部署？

**Comment by dongrentianyu** [comment]
看能不能成功部署？另一个是上次我给你发的插件好像没有提交过去，我在cpl里搜索不到。

**Comment by Zacharia2** [comment]
用什么方式感觉都可以，[TW5-T-ONLINE](https://github.com/Zacharia2/TW5-T-ONLINE)默认使用的是太微中文的部署方式。

**Comment by dongrentianyu** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/211512701-9a0a841d-e404-4129-87f4-cfbc408768b9.png">

你看我用你的模板部署出来的，就会生成这个。不是tiddlywiki的状态

**Comment by Zacharia2** [comment]
你需要设置github pages ，点击仓库的设置，然后点击pages，设置为actions

**Comment by dongrentianyu** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/211513457-847dab38-eff0-46b3-acdb-b24f3ce60d81.png">

这样应该就是设置好了是吧

**Comment by Zacharia2** [comment]
是的

**Comment by dongrentianyu** [comment]
但网站部署效果还是和上面的一样

**Comment by Zacharia2** [comment]
稍等一下，刷新一下就好了

**Comment by dongrentianyu** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/109711900/211514745-7bd04ae8-e158-4c7b-a1d1-ee4dd039c3ab.png">
我觉得是没有在这里设置，但我不清楚该如何设置

**Comment by Zacharia2** [comment]
哦对，我忘记了，你需要放文件到tiddler文件夹里面才可以

**Comment by Zacharia2** [comment]
仅当添加修改条目、插件以及package.json文件时更新GitHub Pages。

**Comment by Zacharia2** [comment]
为了节省计算资源设置的。

**Comment by dongrentianyu** [comment]
不对啊，我现在也需要放进去啊。那作为模板的时候为什么不直接放进去呢

**Comment by dongrentianyu** [comment]
我把gh-pages放到了tiddler的文件夹里，但好像还没有效果

**Comment by Zacharia2** [comment]
不需要gh-pages分支哦。你随便往tiddler文件夹放个文件就可以执行actions了

**Comment by Zacharia2** [comment]
等actions被触发过一会就可以看到wiki了

**Comment by dongrentianyu** [comment]
成功了，但我不知道是为什么。也就是如果我用你的模板，然后我在里面添加一个新的条目，就可以构建了。但为什么同样的操作，我在自己的太记里先建立一个wiki，然后用github desktop同步到github上去，也就是会直接在github上建立一个仓库，但就无法发布了

算了，我回头再测试一次吧

**Comment by Zacharia2** [comment]
需要改一部分的配置。

**Comment by dongrentianyu** [comment]
要怎么修改呢？感觉没有写清楚

**Comment by Zacharia2** [comment]
https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template

**Comment by Zacharia2** [comment]
我把拼图阅读放到社区仓库中了：https://github.com/tiddly-gittly/Jigsaw-reading-split

**Comment by dongrentianyu** [comment]
算了，后面还是都用morden插件部署吧

**Comment by Zacharia2** [comment]
ok
